#+ endpoint: http://data.bibliotheken.nl/sparql
#+ method: GET
#+ isni-lookup:
#+ tags:
#+  - NTA
#+  - ISNI

PREFIX schema: <http://schema.org/>   

SELECT DISTINCT
?id ?person 
(GROUP_CONCAT(DISTINCT(?isni); separator="****") as ?isnis)
(GROUP_CONCAT(DISTINCT(?nta); separator="****") as ?ntas)
(GROUP_CONCAT(DISTINCT(?viaf); separator="****") as ?viafs)
(GROUP_CONCAT(DISTINCT(?wikidata); separator="****") as ?wikidatas)

WHERE{
?person schema:sameAs ?x .
bind(STRAFTER(STR(?x),"http://viaf.org/viaf/") AS ?viaf).
bind(STRAFTER(STR(?x),"http://www.wikidata.org/entity/") AS ?wikidata).
bind(STRAFTER(STR(?x),"https://isni.org/isni/") AS ?isni).  
bind(STRAFTER(STR(?person),"http://data.bibliotheken.nl/id/thes/") AS ?nta).
  
{
SELECT DISTINCT ?person ?id ?_isni 
WHERE {
?person schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/persons> .
?person schema:sameAs ?id.
FILTER(?id = ?_isni).
}
}
} GROUP BY ?person ?id 
