#+ summary: List all NTA-ids (in the NTA set) with their corresponding VIAF, ISNI and Wikidata identifiers
#+ description: List all NTA-ids (in the NTA set) with their corresponding VIAF, ISNI and Wikidata identifiers
#+ endpoint_in_url: False
#+ list-nta-viaf-isni-wdq:
#+ endpoint: http://data.bibliotheken.nl/sparql
#+ method: GET
#+ pagination: 5000
#+ tags:
#+  - NTA
#+  - ISNI
#+  - VIAF
#+  - Wikidata

PREFIX schema: <http://schema.org/>   

SELECT DISTINCT ?nta ?isni ?viaf ?wikidata
WHERE{
?person schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/persons> .
?person schema:sameAs ?id.
BIND(STRAFTER(STR(?person),"http://data.bibliotheken.nl/id/thes/") AS ?nta).
BIND(STRAFTER(STR(?id),"http://www.isni.org/isni/") AS ?isni).
BIND(STRAFTER(STR(?id),"http://viaf.org/viaf/") AS ?viaf).
BIND(STRAFTER(STR(?id),"http://www.wikidata.org/entity/") AS ?wikidata).
} 
