#+     Put in string, find out matching person names in the NTA 
#+ person-lookup:
#+ endpoint: http://data.bibliotheken.nl/sparql
#+ method: GET
#+ tags:
#+  - NTA
#+  - Names


PREFIX schema: <http://schema.org/>   

select ?person ?name where {
  ?person a schema:Person .
  ?person schema:name ?name .
  FILTER(regex(?name, ?_name, 'i'))
} limit 100
