#+ summary: Put in string, find out matching person names in the NTA 
#+ description: Put in string, find out matching person names in the NTA 
#+ endpoint_in_url: False
#+ person-search:
#+ endpoint: http://data.bibliotheken.nl/sparql
#+ method: GET
#+ tags:
#+  - NTA

PREFIX schema: <http://schema.org/>   

select ?person ?name where {
  ?person a schema:Person .
  ?person schema:name ?name .
  FILTER(regex(?name, ?_name, 'i'))
} limit 1000
